providers = ["nodejs"]

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
    "echo 'Building frontend...'",
    "npm run build:web",
    "echo 'Building backend...'", 
    "npm run build:api",
    "echo 'Build completed!'",
    "ls -la dist/ || echo 'dist directory not found'",
    "ls -la dist/public/ || echo 'dist/public directory not found'"
]

[start]
cmd = "npm start"