[build]
builder = "nixpacks"
buildCommand = "npm run build"
watchPatterns = ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10