[build]
builder = "nixpacks"

[deploy]
startCommand = "NODE_OPTIONS='--dns-result-order=ipv4first' npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[experimental]
publicNetworking = true